### ISSUE TITLE
No rule to target 'sign-install'

### ISSUE THREAD

**Issue by ljcoogan** [lwfinger/rtw8852be#10]
I'm trying to install the drivers using secure boot by following the instructions in the readme. They build fine, but when I run 'sudo make sign-install', I receive the response:
`make: *** No rule to make target 'sign-install'.  Stop.`
I'm running kernel 5.18.16 on Fedora 36. Thanks in advance for any help.

**Comment by lwfinger** [comment]
I had not added that part to the Makefile - now available. When you reboot after the sign-install, be careful with the MOK "bluescreen". You MUST install the key "Custom MOK".
