### ISSUE TITLE
driver stopped working on 5.15.59-1 kernel

### ISSUE THREAD

**Issue by saikatm** [lwfinger/rtw8852be#12]
Just updated to 5.15.59-1-MANJARO kernel. 
compiled and installed and rebooted did not work. 

- cd rtw8852be
- make clean
-  make 
- sudo make install
- sudo modprobe -v 8852be
- reboot

**Comment by saikatm** [comment]
just did git pull for the latest commit and recompiled it. WiFi is back!

**Comment by lwfinger** [comment]
Always do a git pull. You never know what changes might be there.

**Comment by saikatm** [comment]
> Always do a git pull. You never know what changes might be there.

thanks man. I don't want the frequent kernel updates on manjaro to break my wifi...

**Comment by saikatm** [comment]
would u sugget using this? https://aur.archlinux.org/packages/rtw8852be-dkms-git OR should I stick with the repo

**Comment by lwfinger** [comment]
It is up to you. If the arch dkms works, then you do not have to build it yourself. As far as I know, their sources for the driver come from this repo.
