### ISSUE TITLE
Does not work on Linux 6 Manjaro(and ubuntu, popos)

### ISSUE THREAD

**Issue by ZykaJiri** [lwfinger/rtw8852be#20]
Hello, the driver does not seem to work on Linux 6 it installs and gets inicialised without any problems but the wifi status does not change and the wifi card is not detected at all. Tried on multiple distributions - Ubuntu, PopOS, Manjaro

Always did a full reboot between reinstalls/configurations. Tried specifying new_id to the wifi module id on Ubuntu, this did not help.
Bluetooth works fine

## Debugging logs
Neofetch:
![image](https://user-images.githubusercontent.com/91685702/187076599-12ec673a-d2a9-44ea-b959-de7feeca5213.png)

dmesg: [dmesg.txt](https://github.com/lwfinger/rtw8852be/files/9439741/dmesg.txt)

lshw: [lshw.txt](https://github.com/lwfinger/rtw8852be/files/9439756/lshw.txt)

lspci -nn: [lspci.txt](https://github.com/lwfinger/rtw8852be/files/9439757/lspci.txt)

## Command outputs
sudo modprobe -v 8852be
> Outputs nothing

sudo modprobe -vr 8852be && sudo modprobe -v 8852be
> rmmod 8852be
> rmmod cfg80211
> insmod /lib/modules/6.0.0-1-MANJARO/kernel/net/wireless/cfg80211.ko.zst 
> insmod /lib/modules/6.0.0-1-MANJARO/kernel/drivers/net/wireless/realtek/rtw89/8852be.ko 

## What worked on 5.15 Linux kernel
- On the same hardware and the same Manjaro installation
- Link to the working 5.15 driver: https://github.com/HRex39/rtl8852be
  - The github page links to this repo for linux 6.0 > 

I hope i provided all the possible relevant information. May have missed something. Thank you for reading this far.

**Comment by lwfinger** [comment]
I had a problem. Do another 'git pull', and all should be OK.

**Comment by ZykaJiri** [comment]
That did it. Thank you very much!

**Comment by lwfinger** [comment]
Do another pull. I fixed the DMA issue.
