### ISSUE TITLE
p2p-device

### ISSUE THREAD

**Issue by juliankiedaisch** [lwfinger/rtw8852be#21]
Miracast with gnome-network-display is not possible due to the missing p2p-device. Is it possible to activate it?
As i understand it, 'iw dev' schould show a p2p-device (type) in addition to the managed (type) wifi-device but with this code, only the managed wifi-device is listed.

**Comment by lwfinger** [comment]
All I know is that CONFIG_P2P is set, thus the driver should be P2P capable. One problem might be that this driver uses cfg80211, but not mac80211. That will limit the capabilities.

Adding this capability would require more knowledge of the chip than I have. I am just a volunteer, not a Realtek employee!
