### ISSUE TITLE
Unable to compile and install the driver, the corresponding platform is missing.

### ISSUE THREAD

**Issue by Sakuraofking** [lwfinger/rtw8852be#28]
There is no general arm64 platform in the platform selection, can you make another configure file, or how to install this driver on the general arm64 platform.
`Kenerl Version:5.4.18-35-generic
OS:Ubuntu Kylin
CPU:HUAWEI Kunpeng 920`

**Comment by lwfinger** [comment]
I modified platform/i386pc.mk to handle arm and aarch64. Do a 'git pull' and keep "CONFIG_PLATFORM_I386_PC = y" in the Makefile and the platform file should produce the correct architecture name.
