### ISSUE TITLE
How do I compile and install this driver on CentOS 7 or 8 and Stream?

### ISSUE THREAD

**Issue by Sakuraofking** [lwfinger/rtw8852be#35]
Due to the specificities of the platform and the software source environment, many dependencies cannot be installed. openSUSE and Fedora software packages cannot be installed on CentOS. Is there a good solution to install this driver on CentOS?

**Comment by Sakuraofking** [comment]
Yes, I've installed kenerl-header, but it's still getting errors. Is there a build-essentials on RedHat Linux？I checked that I need to execute yum groupinstall "Development Libraries" "Development Tools" to install the C++ development environment, but the development library could not be found. Is this related to the software source?Or is there another way? It's been bugging me for a week.

**Comment by lwfinger** [comment]
Well, if you stated at least some of the errors, I might be able to help you.

If this has taken you a week, might I suggest that you switch to another distro that might be better supported? Fedora or openSUSE would still be RPM-based.

**Comment by Sakuraofking** [comment]
Check this out. Maybe this information will help you. I choose CentOS because it needs to run some special software, because the CPU is very special.
`[root@trust ~]# cd rtw8852be/
[root@trust rtw8852be]# make


*******************

IMPORTANT MESSAGE TO ALL USERS

The RTW8852BE driver in https://github.com/lwfinger/rtw89.git is now functional                                                                                                                                                              as of 10-OCT-2022

THIS REPO IS REDUNDANT AND WILL BE REMOVED 1-DEC-2022.

*******************


#rm -f .symvers.8852be
make ARCH=arm64 CROSS_COMPILE= -C /lib/modules/4.18.0-193.28.1.el7.aarch64/build                                                                                                                                                              M=/root/rtw8852be  modules
make[1]: Entering directory `/usr/src/kernels/4.18.0-193.28.1.el7.aarch64'
  CC [M]  /root/rtw8852be/os_dep/linux/rtw_android.o
/root/rtw8852be/os_dep/linux/rtw_android.c: In function ‘rtw_android_priv_cmd’:
/root/rtw8852be/os_dep/linux/rtw_android.c:440:62: error: macro "access_ok" pass                                                                                                                                                             ed 3 arguments, but takes just 2
  if (!access_ok(VERIFY_READ, priv_cmd.buf, priv_cmd.total_len)) {
                                                              ^
/root/rtw8852be/os_dep/linux/rtw_android.c:440:7: error: ‘access_ok’ undeclared                                                                                                                                                              (first use in this function)
  if (!access_ok(VERIFY_READ, priv_cmd.buf, priv_cmd.total_len)) {
       ^
/root/rtw8852be/os_dep/linux/rtw_android.c:440:7: note: each undeclared identifi                                                                                                                                                             er is reported only once for each function it appears in
make[2]: *** [/root/rtw8852be/os_dep/linux/rtw_android.o] Error 1
make[1]: *** [_module_/root/rtw8852be] Error 2
make[1]: Leaving directory `/usr/src/kernels/4.18.0-193.28.1.el7.aarch64'
make: *** [modules] Error 2
[root@trust rtw8852be]#
`

**Comment by lwfinger** [comment]
I do not support kernels as old as 4.18.0. There are just too many changes in newer kernels that greatly improve wifi stability and performance. You need to get something a lot newer!!
