### ISSUE TITLE
can't connect after suspend

### ISSUE THREAD

**Issue by brasta78** [lwfinger/rtw8852be#38]
I have a problem that wifi doesn't reconnect when computer power on after suspend. There is a wifi network SSID list and is stuck trying to connect to default wifi. I'm not an experienced user, but what I see in the log just:

kernel: rtw8852be: Connection disconnected for reason 1

Ubuntu 22.04.01 LTS kernel 6.0.7

**Comment by lwfinger** [comment]
As this driver has been superseded  by https://github.com/lwfinger/rtw89.git, and that it will be deleted on Dec. 1, I am not entertaining any more complaints about this one. If youreally want to use it rather than the kernel version, you are on your own.
