### ISSUE TITLE
is this source code official from Realtek?

### ISSUE THREAD

**Issue by hungtooc** [lwfinger/rtw8852be#39]

**Comment by lwfinger** [comment]
Yes. This code is developed by Realtek's factory to test chips when they are manufactured. There is considerable code needed for this purpose. For example, this driver for RTW8852BE is over 700,000 lines of code. By contrast, the driver in https://github.com/lwfinger/rtw90.git has a little over 200,000 loc, and it handles RTW8852AE, RTW8852BE, and RTW8852CE! For rtw88, the wifi5 driver, a patch set to include 4 USB drivers is a little over 2000 lines, and rtw89 has the same kind of structure. Incidentally, this repo will be deleted later today. rtw89 has the driver that will be in the 6.2 kernel, yet still build and run for kernels >= 5.5.
