### ISSUE TITLE
PCIe Make install error in kernel-5.10

### ISSUE THREAD

**Issue by wufenghui** [lwfinger/rtw8852be#41]

**Comment by wufenghui** [comment]
![1695690949063](https://github.com/lwfinger/rtw8852be/assets/58621891/e8a9fdfd-410b-457b-b416-5d9ffac35a2b)

**Comment by wufenghui** [comment]
![1695690949063](https://github.com/lwfinger/rtw8852be/assets/58621891/3262e4fc-f9f2-4c25-b859-58b5f7348494)

**Comment by lwfinger** [comment]
I have no idea what is going wrong. I have never seen errors of this sort.

The one thing I have to say is that with an rtw8852be, and a 5.10 kernel, you should be using the rtw89 repo. I provided the one that you are using before rtw89 was ready; however, I no longer maintain the vendor driver.

**Comment by wufenghui** [comment]
> I have no idea what is going wrong. I have never seen errors of this sort.
> 
> The one thing I have to say is that with an rtw8852be, and a 5.10 kernel, you should be using the rtw89 repo. I provided the one that you are using before rtw89 was ready; however, I no longer maintain the vendor driver.

Can you provide a PCIe driver version that matches the kernel-5.10

**Comment by lwfinger** [comment]
Yes, https://github.com/lwfinger/rtw89.git will build on kernels newer than 5.4.
