### ISSUE TITLE
what's  the different between rtl8852be and rtw8852be? 

### ISSUE THREAD

**Issue by 903859154** [lwfinger/rtw8852be#42]
as the title said

**Comment by 903859154** [comment]
my device is rtl8852be, can i use your rtw8852be driver?

**Comment by lwfinger** [comment]
The chip name is RTL8852BE (Notice the upper case.), but the driver is rtw8852be (lower case).

It is not "my" driver. It is the driver from the latest kernel, backported to older kernels. It was written by the PCI group at Realtek.
